name: Deploy to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Fetch API URL
      run: |
        aws s3 cp s3://cf-resume-site-share/api_url.txt .
        API_URL=$(cat api_url.txt)
        echo "API_URL=$API_URL" >> $GITHUB_ENV

    - name: Update index.html with API URL
      run: |
        sed -i "s|API_URL_PLACEHOLDER|${{ env.API_URL }}|" index.html

    - name: Deploy to S3
      run: |
        aws s3 sync . s3://chandler-backend-testing-bucket  --delete

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id E2P9LX9B5OBRWA --paths "/*"

    - name: Notify SNS
      if: success()
      run: |
        aws sns publish \
          --topic-arn ${{ secrets.SNS_TOPIC_ARN }} \
          --message "Website update successful. Deployed commit: ${{ github.sha }}"